Version 11.17
Traceback (most recent call last):
  File "lucas.py", line 49, in <module>
  File "Code\Init.pyo", line 35, in init
    
WindowsError: [Error 2] The system cannot find the file specified: 'Lucas.exe'
Traceback (most recent call last):
  File "lucas.py", line 49, in <module>
  File "Code\Init.pyo", line 35, in init
    
WindowsError: [Error 2] The system cannot find the file specified: 'Lucas.exe'
Traceback (most recent call last):
  File "Code\QT\WBase.pyo", line 281, in procesarAccion
    
  File "Code\Procesador.pyo", line 515, in procesarAccion
    
  File "Code\Procesador.pyo", line 868, in informacion
    
  File "Code\Procesador.pyo", line 872, in informacion_run
    
  File "Code\Procesador.pyo", line 899, in acercade
    
  File "Code\QT\Info.pyo", line 39, in __init__
    
  File "Code\QT\InfoBase.pyo", line 93, in texto
    
  File "Code\QT\InfoBase.pyo", line 194, in Translators
    
  File "Code\QT\InfoBase.pyo", line 192, in r
    
KeyError: 'AUTHOR'
Traceback (most recent call last):
  File "Code\QT\WBase.pyo", line 281, in procesarAccion
    
  File "Code\Procesador.pyo", line 515, in procesarAccion
    
  File "Code\Procesador.pyo", line 868, in informacion
    
  File "Code\Procesador.pyo", line 872, in informacion_run
    
  File "Code\Procesador.pyo", line 899, in acercade
    
  File "Code\QT\Info.pyo", line 39, in __init__
    
  File "Code\QT\InfoBase.pyo", line 93, in texto
    
  File "Code\QT\InfoBase.pyo", line 194, in Translators
    
  File "Code\QT\InfoBase.pyo", line 192, in r
    
KeyError: 'AUTHOR'
Traceback (most recent call last):
  File "Code\QT\WBase.pyo", line 281, in procesarAccion
    
  File "Code\Procesador.pyo", line 515, in procesarAccion
    
  File "Code\Procesador.pyo", line 868, in informacion
    
  File "Code\Procesador.pyo", line 872, in informacion_run
    
  File "Code\Procesador.pyo", line 899, in acercade
    
  File "Code\QT\Info.pyo", line 39, in __init__
    
  File "Code\QT\InfoBase.pyo", line 93, in texto
    
  File "Code\QT\InfoBase.pyo", line 194, in Translators
    
  File "Code\QT\InfoBase.pyo", line 192, in r
    
KeyError: 'AUTHOR'
